apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: ping
spec:
  replicas: 1
  selector:
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - name: ping
        image: patrocinio/ping_pong
        env:
        - name: QUEUE
          value: "ping"
        - name: OTHER_QUEUE
          value: "pong"
