apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: ping
spec:
  replicas: 2
  selector:
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - name: ping
        image: patrocinio/ping_pong
        env:
        - name: QUEUE_NAME
          value: "ping"
        - name: OTHER_QUEUE_NAME
          value: "pong"
        - name:  QUEUE 
          value: "queue-rabbitmq.ping-pong.svc.cluster.local"
